steps:
  # =====================================================
  # 1. Build Docker Image
  # =====================================================
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"
      - "."

  # =====================================================
  # 2. Push Image to Artifact Registry
  # =====================================================
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"

  # =====================================================
  # 3. Deploy to GKE (private cluster)
  #    Uses gke-deploy to apply manifests from kube-files/
  # =====================================================
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kube-files/"
      - "--image=us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"
      - "--location=us-central1"
      - "--cluster=challenge-gke"

# =====================================================
# Images produced
# =====================================================
images:
  - "us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"

# =====================================================
# IMPORTANT: Use the PRIVATE WORKER POOL
# =====================================================
options:
  pool:
    name: "projects/mc-abdulhmeed-bk-sandbox1/locations/us-central1/workerPools/challenge-build-pool"
logging: CLOUD_LOGGING_ONLY