steps:
  # =====================================================
  # 1. Build Docker Image
  # =====================================================
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"
      - "."

  # =====================================================
  # 2. Push Image to Artifact Registry
  # =====================================================
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"

  # =====================================================
  # 3. Deploy to GKE (private cluster) using kube-files/
  # =====================================================
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - "--filename=kube-files/"
      - "--image=us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"
      - "--location=us-central1"
      - "--cluster=challenge-gke"

images:
  - "us-central1-docker.pkg.dev/mc-abdulhmeed-bk-sandbox1/webapp/webapp:$SHORT_SHA"

options:
  # Use your PRIVATE worker pool
  pool:
    name: "projects/mc-abdulhmeed-bk-sandbox1/locations/us-central1/workerPools/challenge-build-pool"

  # Satisfy the org/logging requirement for custom service accounts
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
