steps:

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      "build",
      "-t",
      "$LOCATION-docker.pkg.dev/$PROJECT_ID/webapp/webapp:$SHORT_SHA",
      "."
    ]


- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      "push",
      "$LOCATION-docker.pkg.dev/$PROJECT_ID/webapp/webapp:$SHORT_SHA"
    ]


- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    [
      "run",
      "--filename=kube-files",            
      "--image=$LOCATION-docker.pkg.dev/$PROJECT_ID/webapp/webapp:$SHORT_SHA",
      "--location=us-central1",
      "--cluster=challenge-gke"
    ]


options:
  logging: CLOUD_LOGGING_ONLY
